version: "3.9"
services:
  server:
    build: ./server
    container_name: books_server
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - /app/node_modules
  nginx:
    build: ./nginx
    restart: always
    container_name: nginx_proxy_api
    ports: 
      - 80:80
    